name: Node Harvest

on:
  workflow_dispatch:
  push:
    paths:
      - 'urls.txt'
  schedule:
    - cron: '0 */6 * * *' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4 # 修正了这里的拼写
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Run convert script
        run: python convert.py

      - name: Commit and Push
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add clash.yaml
          git commit -m "Timed Update: HY2 nodes only" || exit 0
          git push
